version: '3.9'
services:
  influxdb:
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory and configuration
      - ./docker/influxdb/data:/var/lib/influxdb2:rw
    ports:
      - 8086:8086
    networks:
      - plantbuddy
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup 
      - DOCKER_INFLUXDB_INIT_USERNAME=plantbuddy
      - DOCKER_INFLUXDB_INIT_PASSWORD=plantbuddy
      - DOCKER_INFLUXDB_INIT_ORG=plantbuddy 
      - DOCKER_INFLUXDB_INIT_BUCKET=plantbuddy
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=plantbuddy
  plantbuddy:
    image: plantbuddy:latest
    ports:
      - 5001:5001
    networks:
      - plantbuddy
    environment:
      - PLANTBUDDY_SETTINGS=default_settings.py 
# Linux only. Will not work on MAC due to incompatability to mount USB devices
  #telegraf:
   # image: telegraf-plantbuddy:latest
    #networks:
     # - plantbuddy
    #volumes:
     # - ./docker/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
     # - ./docker/telegraf/serial_read_telegraf.py:/app/serial_read_telegraf.py
     # environment:
     # - SERIAL_PORT=/dev/cu.usbmodem143301
    # devices:
    #  - "/dev/cu.usbmodem143301:/dev/cu.usbmodem143301"
    #privileged: true
networks: 
  plantbuddy:
    name: plantbuddy