from(bucket: "plantbuddy")
    |> range(start: -1h)
    |> filter(fn: (r) => r["_measurement"] == "sensor_data")
    |> filter(fn: (r) => r["device_id"] == "eui-323932326d306512")
    |> filter(fn: (r) => r["_field"] == "light")