from(bucket: "plantbuddy")
    |> range(start: -24h)
    |> filter(fn: (r) => r["_measurement"] == "sensor_data")
    |> filter(fn: (r) => r["device_id"] == "01")
    |> filter(fn: (r) => r["_field"] == "air_temperature")